# This is a basic workflow to help you get started with Actions

name: Generate from Backup

# Controls when the workflow will run
on:
  workflow_dispatch:
      sheet_id:
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  fetch:
    environment: googleapi
    
    permissions:
      contents: "read"
      id-token: "write"
      
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"
          cache-dependency-path: package/package-lock.json

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          # 外部から切り替えできるように secret にしてある.
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - run: npm ci
        working-directory: package
      - run: npm run generate ${{ github.event.inputs.sheet_id }}
        working-directory: package